services:
  code2vec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code2vec4js
    volumes:
      - ./:/code2vec/
      # - /mnt/data1/kazuya-s/dataset/data/jsPerf:/data
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
    working_dir: /code2vec
