version: "3"
services:
  code2vec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code2vec
    volumes:
      - ./:/code2vec/
      - /Users/kazuya/GitHub/Script-for-Research/data_organization/data/jsPerf:/data
    stdin_open: true
    working_dir: /code2vec
