version: "3"
services:
  code2vec:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    container_name: code2vec2
    volumes:
      - ./:/code2vec/
      - /mnt/data1/kazuya-s/dataset/data/jsPerf:/data
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    working_dir: /code2vec
