version: "3"
services:
  code2vec:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    container_name: code2vec
    volumes:
      - ./:/code2vec/
      - /Users/kazuya/GitHub/Script-for-Research/data_organization/data/jsPerf:/data
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    working_dir: /code2vec
